#!/usr/bin/env python3
"""
evaluate_multivariate.py

Evaluate multivariate synthetic time series generated by unconditional diffusion.

- Real: .npy with shape (N, T, C)
- Synth: .npy with shape (N, T, C)  (or (N, T) for univariate; handled)

Outputs:
- metrics.json
- plots: per-channel sequences, hist, acf, fft

Example:
python evaluate_multivariate.py \
  --real ../data/diffusion_ready/appliances/test_seq.npy \
  --synth synthetic_samples_sssds4.npy \
  --outdir eval_sssds4 \
  --channels 28 \
  --n_plots 3 \
  --plot_channels 0 1 2 5 \
  --seed 0
"""

import argparse
from pathlib import Path
import json
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import acf

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler


# ----------------------------
# Summary feature extractor (multivariate)
# ----------------------------
def extract_features(X: np.ndarray) -> np.ndarray:
    """
    X: (N, T, C)
    Returns: (N, F) features concatenated across channels
    """
    assert X.ndim == 3, f"Expected (N,T,C), got shape {X.shape}"
    N, T, C = X.shape

    lags = [1, 2, 6, 12, 24]
    feats_all = []

    for c in range(C):
        Xc = X[:, :, c]  # (N,T)

        mean = Xc.mean(axis=1)
        std = Xc.std(axis=1)
        minv = Xc.min(axis=1)
        maxv = Xc.max(axis=1)

        # ACF at a few lags (cheap + informative)
        acfs = []
        for lag in lags:
            if lag >= T:
                acfs.append(np.zeros(N, dtype=np.float32))
            else:
                x1 = Xc[:, lag:]
                x2 = Xc[:, :-lag]
                x1m = x1.mean(axis=1, keepdims=True)
                x2m = x2.mean(axis=1, keepdims=True)
                num = ((x1 - x1m) * (x2 - x2m)).mean(axis=1)
                den = x1.std(axis=1) * x2.std(axis=1) + 1e-8
                acfs.append(num / den)
        acfs = np.stack(acfs, axis=1)  # (N, len(lags))

        # Power spectrum summary
        ps = np.abs(np.fft.rfft(Xc, axis=1)) ** 2  # (N, T_fft)
        ps_mean = ps.mean(axis=1)
        ps_std = ps.std(axis=1)

        feats_c = np.column_stack([mean, std, minv, maxv, ps_mean, ps_std, acfs])
        feats_all.append(feats_c)

    return np.concatenate(feats_all, axis=1)


# ----------------------------
# MMD (RBF kernel)
# ----------------------------
def rbf_mmd(X: np.ndarray, Y: np.ndarray, gamma=None) -> float:
    """
    X, Y: (N, F)
    """
    if gamma is None:
        Z = np.vstack([X, Y])
        idx = np.random.choice(len(Z), size=min(1000, len(Z)), replace=False)
        Zs = Z[idx]
        dists = np.sum((Zs[:, None, :] - Zs[None, :, :]) ** 2, axis=-1)
        med = np.median(dists[dists > 0]) if np.any(dists > 0) else 1.0
        gamma = 1.0 / (2.0 * med + 1e-8)

    def k(A, B):
        d = np.sum((A[:, None, :] - B[None, :, :]) ** 2, axis=-1)
        return np.exp(-gamma * d)

    Kxx = k(X, X)
    Kyy = k(Y, Y)
    Kxy = k(X, Y)

    mmd2 = Kxx.mean() + Kyy.mean() - 2 * Kxy.mean()
    return float(np.sqrt(max(mmd2, 0.0)))


# ----------------------------
# Plots
# ----------------------------
def save_plot_sequences(real, synth, outdir: Path, n=3, ch=0):
    plt.figure(figsize=(12, 4))
    for i in range(min(n, len(real))):
        plt.plot(real[i, :, ch])
    plt.title(f"Real sequences (first {n}) — channel {ch}")
    plt.tight_layout()
    plt.savefig(outdir / f"real_sequences_ch{ch}.png", dpi=150)
    plt.close()

    plt.figure(figsize=(12, 4))
    for i in range(min(n, len(synth))):
        plt.plot(synth[i, :, ch])
    plt.title(f"Synthetic sequences (first {n}) — channel {ch}")
    plt.tight_layout()
    plt.savefig(outdir / f"synthetic_sequences_ch{ch}.png", dpi=150)
    plt.close()


def save_plot_hist(real, synth, outdir: Path, ch=0):
    plt.figure(figsize=(8, 4))
    plt.hist(real[:, :, ch].flatten(), bins=100, density=True, alpha=0.5, label="Real")
    plt.hist(synth[:, :, ch].flatten(), bins=100, density=True, alpha=0.5, label="Synthetic")
    plt.legend()
    plt.title(f"Value distribution — channel {ch}")
    plt.tight_layout()
    plt.savefig(outdir / f"hist_ch{ch}.png", dpi=150)
    plt.close()


def save_plot_acf(real, synth, outdir: Path, ch=0, nlags=60):
    acf_real = acf(real[:, :, ch].flatten(), nlags=nlags)
    acf_synth = acf(synth[:, :, ch].flatten(), nlags=nlags)

    plt.figure(figsize=(8, 4))
    plt.plot(acf_real, label="Real")
    plt.plot(acf_synth, label="Synthetic")
    plt.legend()
    plt.title(f"Autocorrelation — channel {ch}")
    plt.tight_layout()
    plt.savefig(outdir / f"acf_ch{ch}.png", dpi=150)
    plt.close()


def save_plot_fft(real, synth, outdir: Path, ch=0):
    rf = np.mean(np.abs(np.fft.rfft(real[:, :, ch], axis=1)) ** 2, axis=0)
    sf = np.mean(np.abs(np.fft.rfft(synth[:, :, ch], axis=1)) ** 2, axis=0)

    plt.figure(figsize=(8, 4))
    plt.plot(rf, label="Real")
    plt.plot(sf, label="Synthetic")
    plt.legend()
    plt.title(f"Power spectrum — channel {ch}")
    plt.tight_layout()
    plt.savefig(outdir / f"fft_ch{ch}.png", dpi=150)
    plt.close()


# ----------------------------
# Main
# ----------------------------
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--real", required=True, help="Path to real dataset .npy (N,T,C)")
    parser.add_argument("--synth", required=True, help="Path to synthetic samples .npy (N,T,C)")
    parser.add_argument("--outdir", required=True, help="Output directory for metrics + plots")

    parser.add_argument("--channels", type=int, default=None, help="Expected number of channels (optional check)")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--n_plots", type=int, default=3)
    parser.add_argument("--plot_channels", type=int, nargs="*", default=[0],
                        help="Which channels to plot (e.g. --plot_channels 0 1 5)")

    parser.add_argument("--max_samples", type=int, default=None,
                        help="Optionally cap number of samples used for metrics (speed)")

    args = parser.parse_args()
    np.random.seed(args.seed)

    real_path = Path(args.real)
    synth_path = Path(args.synth)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    # Load
    real = np.load(real_path)
    synth = np.load(synth_path)

    # Normalize shapes to (N,T,C)
    if real.ndim == 2:
        real = real[:, :, None]
    if synth.ndim == 2:
        synth = synth[:, :, None]
    if synth.ndim == 3 and synth.shape[-1] == 1 and real.shape[-1] != 1:
        # if someone saved (N,T,1) but real is multivariate, keep as-is
        pass

    assert real.ndim == 3 and synth.ndim == 3, f"Shapes must be (N,T,C). Got real={real.shape}, synth={synth.shape}"

    # Optional channel check
    if args.channels is not None:
        if real.shape[-1] != args.channels:
            print(f"[warn] real channels C={real.shape[-1]} != --channels {args.channels}")
        if synth.shape[-1] != args.channels:
            print(f"[warn] synth channels C={synth.shape[-1]} != --channels {args.channels}")

    # Make sizes comparable for classifier fairness
    n = min(len(real), len(synth))
    if args.max_samples is not None:
        n = min(n, args.max_samples)

    real_sub = real[:n]
    synth_sub = synth[:n]

    # ----- Metrics -----
    feats_real = extract_features(real_sub)
    feats_synth = extract_features(synth_sub)

    # Discriminative AUC
    X = np.vstack([feats_real, feats_synth])
    y = np.hstack([np.zeros(len(feats_real)), np.ones(len(feats_synth))])

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=args.seed, stratify=y
    )

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    clf = LogisticRegression(max_iter=2000)
    clf.fit(X_train, y_train)
    y_score = clf.predict_proba(X_test)[:, 1]
    auc = float(roc_auc_score(y_test, y_score))

    # MMD
    mmd = rbf_mmd(feats_real, feats_synth)

    metrics = {
        "real_mean": float(real_sub.mean()),
        "real_std": float(real_sub.std()),
        "synth_mean": float(synth_sub.mean()),
        "synth_std": float(synth_sub.std()),
        "discriminative_auc": auc,
        "mmd_rbf": mmd,
        "n_real_used": int(real_sub.shape[0]),
        "n_synth_used": int(synth_sub.shape[0]),
        "seq_len": int(real_sub.shape[1]),
        "channels": int(real_sub.shape[2]),
        "real_path": str(real_path.resolve()),
        "synth_path": str(synth_path.resolve()),
        "seed": int(args.seed),
    }

    # Save metrics
    with open(outdir / "metrics.json", "w") as f:
        json.dump(metrics, f, indent=2)

    # Plots
    for ch in args.plot_channels:
        if ch < 0 or ch >= real_sub.shape[2]:
            print(f"[warn] requested plot channel {ch} out of range (0..{real_sub.shape[2]-1}), skipping")
            continue
        save_plot_sequences(real_sub, synth_sub, outdir, n=args.n_plots, ch=ch)
        save_plot_hist(real_sub, synth_sub, outdir, ch=ch)
        save_plot_acf(real_sub, synth_sub, outdir, ch=ch)
        save_plot_fft(real_sub, synth_sub, outdir, ch=ch)

    print("Saved evaluation to:", outdir)
    print(json.dumps(metrics, indent=2))


if __name__ == "__main__":
    main()